/* Auto-generated by snesrecomp v2 tools/v2_sync_funcs_h.py.
 * Do NOT hand-edit. Every recompiled function takes a
 * CpuState* and mutates it in place — no return values, no
 * register-packed structs. Drop custom typedefs (HdmaPtrs,
 * PairU8, OwHvPos, CollInfo, ExtCollOut, CheckPlatformCollRet,
 * CalcTiltPlatformArgs) — all v1 ABI fiction, gone.
 *
 * Per-(m, x) variants: every named function is declared in
 * five forms so cross-bank generated calls can reference any
 * variant without a side-car header dependency. Unused
 * variants are harmless (C only flags undefined REFERENCES,
 * not undefined DECLARATIONS at link time).
 */
#pragma once

#include "cpu_state.h"

/* 17 functions across all banks (5 decls each). */

void ResetHandler(CpuState *cpu);  /* $00:8007 alias */
RecompReturn ResetHandler_M0X0(CpuState *cpu);
RecompReturn ResetHandler_M0X1(CpuState *cpu);
RecompReturn ResetHandler_M1X0(CpuState *cpu);
RecompReturn ResetHandler_M1X1(CpuState *cpu);
void SoftReset(CpuState *cpu);  /* $00:8016 alias */
RecompReturn SoftReset_M0X0(CpuState *cpu);
RecompReturn SoftReset_M0X1(CpuState *cpu);
RecompReturn SoftReset_M1X0(CpuState *cpu);
RecompReturn SoftReset_M1X1(CpuState *cpu);
void MainLoopStub(CpuState *cpu);  /* $00:8099 alias */
RecompReturn MainLoopStub_M0X0(CpuState *cpu);
RecompReturn MainLoopStub_M0X1(CpuState *cpu);
RecompReturn MainLoopStub_M1X0(CpuState *cpu);
RecompReturn MainLoopStub_M1X1(CpuState *cpu);
void TaskDie(CpuState *cpu);  /* $00:80F8 alias */
RecompReturn TaskDie_M0X0(CpuState *cpu);
RecompReturn TaskDie_M0X1(CpuState *cpu);
RecompReturn TaskDie_M1X0(CpuState *cpu);
RecompReturn TaskDie_M1X1(CpuState *cpu);
void YieldOneFrame(CpuState *cpu);  /* $00:8100 alias */
RecompReturn YieldOneFrame_M0X0(CpuState *cpu);
RecompReturn YieldOneFrame_M0X1(CpuState *cpu);
RecompReturn YieldOneFrame_M1X0(CpuState *cpu);
RecompReturn YieldOneFrame_M1X1(CpuState *cpu);
void YieldNFrames(CpuState *cpu);  /* $00:810C alias */
RecompReturn YieldNFrames_M0X0(CpuState *cpu);
RecompReturn YieldNFrames_M0X1(CpuState *cpu);
RecompReturn YieldNFrames_M1X0(CpuState *cpu);
RecompReturn YieldNFrames_M1X1(CpuState *cpu);
void YieldVblank(CpuState *cpu);  /* $00:8121 alias */
RecompReturn YieldVblank_M0X0(CpuState *cpu);
RecompReturn YieldVblank_M0X1(CpuState *cpu);
RecompReturn YieldVblank_M1X0(CpuState *cpu);
RecompReturn YieldVblank_M1X1(CpuState *cpu);
void NmiHandler(CpuState *cpu);  /* $00:8168 alias */
RecompReturn NmiHandler_M0X0(CpuState *cpu);
RecompReturn NmiHandler_M0X1(CpuState *cpu);
RecompReturn NmiHandler_M1X0(CpuState *cpu);
RecompReturn NmiHandler_M1X1(CpuState *cpu);
void IrqHandler(CpuState *cpu);  /* $00:84A1 alias */
RecompReturn IrqHandler_M0X0(CpuState *cpu);
RecompReturn IrqHandler_M0X1(CpuState *cpu);
RecompReturn IrqHandler_M1X0(CpuState *cpu);
RecompReturn IrqHandler_M1X1(CpuState *cpu);
void Task0(CpuState *cpu);  /* $00:852C alias */
RecompReturn Task0_M0X0(CpuState *cpu);
RecompReturn Task0_M0X1(CpuState *cpu);
RecompReturn Task0_M1X0(CpuState *cpu);
RecompReturn Task0_M1X1(CpuState *cpu);
void Task_89C9(CpuState *cpu);  /* $00:89C9 alias */
RecompReturn Task_89C9_M0X0(CpuState *cpu);
RecompReturn Task_89C9_M0X1(CpuState *cpu);
RecompReturn Task_89C9_M1X0(CpuState *cpu);
RecompReturn Task_89C9_M1X1(CpuState *cpu);
void Task_89DB(CpuState *cpu);  /* $00:89DB alias */
RecompReturn Task_89DB_M0X0(CpuState *cpu);
RecompReturn Task_89DB_M0X1(CpuState *cpu);
RecompReturn Task_89DB_M1X0(CpuState *cpu);
RecompReturn Task_89DB_M1X1(CpuState *cpu);
void Task_B091(CpuState *cpu);  /* $00:B091 alias */
RecompReturn Task_B091_M0X0(CpuState *cpu);
RecompReturn Task_B091_M0X1(CpuState *cpu);
RecompReturn Task_B091_M1X0(CpuState *cpu);
RecompReturn Task_B091_M1X1(CpuState *cpu);
void Task_B25B(CpuState *cpu);  /* $00:B25B alias */
RecompReturn Task_B25B_M0X0(CpuState *cpu);
RecompReturn Task_B25B_M0X1(CpuState *cpu);
RecompReturn Task_B25B_M1X0(CpuState *cpu);
RecompReturn Task_B25B_M1X1(CpuState *cpu);
void Task_B38D(CpuState *cpu);  /* $00:B38D alias */
RecompReturn Task_B38D_M0X0(CpuState *cpu);
RecompReturn Task_B38D_M0X1(CpuState *cpu);
RecompReturn Task_B38D_M1X0(CpuState *cpu);
RecompReturn Task_B38D_M1X1(CpuState *cpu);
void Task_B436(CpuState *cpu);  /* $00:B436 alias */
RecompReturn Task_B436_M0X0(CpuState *cpu);
RecompReturn Task_B436_M0X1(CpuState *cpu);
RecompReturn Task_B436_M1X0(CpuState *cpu);
RecompReturn Task_B436_M1X1(CpuState *cpu);
void Task_E6B1(CpuState *cpu);  /* $00:E6B1 alias */
RecompReturn Task_E6B1_M0X0(CpuState *cpu);
RecompReturn Task_E6B1_M0X1(CpuState *cpu);
RecompReturn Task_E6B1_M1X0(CpuState *cpu);
RecompReturn Task_E6B1_M1X1(CpuState *cpu);

/* Hand-written non-recompiled bodies still declared here.
 * These are not produced by the v2 emit pipeline but are
 * referenced by recompiled code via funcs.h.
 */
void ResetSpritesFunc(int wh);
void RunOneFrameOfGame_Internal(void);

/* Watchdog hook called at every block label. Implemented in
 * snesrecomp/runner/src/common_cpu_infra.c.
 */
void WatchdogCheck(void);
